spring:
  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    path: "/api-docs"

open-weather-map:
  api-key: ${API_KEY}
  api-url: https://api.openweathermap.org/data/2.5/weather